{% set name = "scikit-criteria" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-criteria-{{ version }}.tar.gz
  sha256: e1fe346c6c1fcc18227ec7f08f978345fb13a81892f055b65bb9fb9f72259339

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - pandas
    - pyquery
    - scipy
    - jinja2
    - custom-inherit
    - seaborn
    - pulp
    - deprecated
    - scikit-learn
    - importlib_metadata
    - matplotlib-base !=3.6.1

test:
  imports:
    - skcriteria
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://scikit-criteria.org/
  summary: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific python stack. Is Open source and commercially usable.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
