{% set name = "scikit-criteria" %}
{% set version = "0.8.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quatrope/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: e004dd6492b12532959df7ac8e0469c4a6f71d0f6dcf787c30d7ef23f7d72aba
  patches:   # [win]
    - patches/0001-fix-dtype-inference-issues-for-tests-on-win.patch  # [win]
    - patches/0002-fix-dtype-inference-issues-for-tests-on-win.patch  # [win]
    - patches/0003-fix-dtype-inference-issues-for-tests-on-win.patch  # [win]
    - patches/0004-fix-dtype-inference-issues-for-tests-on-win.patch  # [win]
    - patches/0005-do-not-use-assert-frame_equals.patch               # [win]

build:
  # skip s390x because of missing pulp for s390x
  skip: True  # [s390x]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pandas
    - scipy
    - jinja2
    - custom-inherit
    - seaborn
    - deprecated
    - pulp
    - scikit-learn >=1.3,<1.4
    - importlib_metadata
    - matplotlib-base !=3.6.1
    - methodtools

# skipping test_is_available because pulp solvers involved in test are supposed to be installed as separate
# dependencies but are not strictly necessary for pulp to work (default solver is COIN_CMD)
{% set tests_to_skip = "test_is_available" %}
# skipping test_StdWeighter as the assertion that fails has to do with machine precision when performing matrix
# calculation --> results make sense minus negligible errors
{% set tests_to_skip = tests_to_skip + " or test_StdWeighter" %}
# skipping test_RatioMOORA_kracka2010ranking as on windows it presents major deviations from expected results
# likely a computational issue deriving from pandas.DataFrame dtype being wrongly inferred on win-64
{% set tests_to_skip = tests_to_skip + " or test_RatioMOORA_kracka2010ranking" %}  # [win]


test:
  imports:
    - skcriteria
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests -k "not ({{ tests_to_skip }})"
  requires:
    - pip
    - pytest
    - pytest-ordering
    - pyquery
    - tk  # [win]

about:
  home: https://scikit-criteria.quatrope.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Scikit-Criteria is a collection of Multiple-criteria decision analysis methods integrated into python.
  description: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific
    python stack. Is Open source and commercially usable.
  doc_url: https://scikit-criteria.quatrope.org/en/latest/tutorial/index.html
  dev_url: https://github.com/quatrope/scikit-criteria


extra:
  recipe-maintainers:
    - hadim
