{% set name = "scikit-criteria" %}
{% set version = "0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-criteria-{{ version }}.tar.gz
  sha256: 75edbd80dd61e853ec06a89f7e374f4c3a9c931a28db8944ed0d30252a7ed3af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - pandas
    - pyquery
    - scipy
    - jinja2
    - custom-inherit
    - seaborn
    - pulp
    - deprecated

test:
  imports:
    - skcriteria
  commands:
    - pip check
  requires:
    - pip
#     - mock  # for `pip check`
#     - pytest  # for `pip check`

about:
  home: http://scikit-criteria.org/
  summary: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific python stack. Is Open source and commercially usable.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
