{% set name = "scikit-criteria" %}
{% set version = "0.8.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-criteria-{{ version }}.tar.gz
  sha256: d3cda3103ba8030409de8804ddcfceba596faf4897cc4798766d6d171e0437d9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pandas
    - scipy
    - jinja2
    - custom-inherit
    - seaborn
    - deprecated
    - pulp
    - scikit-learn >=1.3,<1.4
    - importlib_metadata
    - matplotlib-base !=3.6.1
    - methodtools

test:
  imports:
    - skcriteria
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://scikit-criteria.quatrope.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Scikit-Criteria is a collection of Multiple-criteria decision analysis methods integrated into python.
  description: |
    Scikit-Criteria is a collection of Multiple-criteria decision analysis (MCDA) methods integrated into scientific
    python stack. Is Open source and commercially usable.
  doc_url: https://scikit-criteria.quatrope.org/en/latest/tutorial/index.html
  dev_url: https://github.com/quatrope/scikit-criteria


extra:
  recipe-maintainers:
    - hadim
